"""API routers package."""

from app.interfaces.api.routers import (
    admin,
    analytics,
    appeals,
    auth,
    auto_sop,
    calls,
    coaching,
    dashboard,
    datasets,
    forecast,
    fraud,
    health,
    live_assistant,
    memory_graph,
    multi_product,
    personality,
    pragmatics,
    qa,
    revenue_leak,
    rules,
    scoring,
    simulator,
)

__all__ = [
    "admin",
    "analytics",
    "appeals",
    "auth",
    "auto_sop",
    "calls",
    "coaching",
    "dashboard",
    "datasets",
    "forecast",
    "fraud",
    "health",
    "live_assistant",
    "memory_graph",
    "multi_product",
    "personality",
    "pragmatics",
    "qa",
    "revenue_leak",
    "rules",
    "scoring",
    "simulator",
]
