import type {
  AdminUser,
  AnalysisResult,
  Appeal,
  AuthTokens,
  CallSummary,
  CoachingPlan,
  DashboardOverview,
  QaQueueItem,
  RulebookRule,
} from "./types";

export const DEMO_PASSWORD = "demo1234";

export function demoLogin(email: string, password: string): AuthTokens {
  void password;
  const isAdmin = email.includes("admin") || email.includes("qa");
  return {
    access_token: "demo.jwt.access",
    refresh_token: "demo.jwt.refresh",
    token_type: "bearer",
    expires_in: 3600,
    user: {
      id: "us_demo_001",
      email: email || "lead@acme.vn",
      full_name: isAdmin ? "Trần QA Manager" : "Nguyễn Văn Lead",
      roles: isAdmin ? ["qa_manager", "admin"] : ["team_lead"],
      permissions: [
        "calls:read",
        "scorecard:read",
        "scorecard:override",
        "rulebook:read",
        "coaching:read",
        "coaching:manage",
        "revenue:read",
        "admin:users",
        "audit:read",
      ],
      team_id: "tm_hn1",
      team_name: "HN-Outbound-1",
    },
  };
}

export const DEMO_CALLS: CallSummary[] = [
  {
    id: "cl_1001",
    external_call_id: "dialer-998877",
    agent_user_id: "us_a01",
    agent_name: "Lê Thị Mai",
    campaign_code: "SOAP-99K",
    status: "scored",
    started_at: "2026-09-05T09:58:00Z",
    duration_sec: 372,
    crm_outcome: "callback",
    overall_score: 62.5,
    result: "fail",
    customer_phone_masked: "+84***4567",
  },
  {
    id: "cl_1002",
    external_call_id: "dialer-998901",
    agent_user_id: "us_a02",
    agent_name: "Phạm Minh Đức",
    campaign_code: "SOAP-99K",
    status: "scored",
    started_at: "2026-09-05T10:12:00Z",
    duration_sec: 418,
    crm_outcome: "won",
    overall_score: 88.0,
    result: "pass",
    customer_phone_masked: "+84***1122",
  },
  {
    id: "cl_1003",
    external_call_id: "dialer-998944",
    agent_user_id: "us_a03",
    agent_name: "Hoàng Thu Hà",
    campaign_code: "BDS-VIEW",
    status: "needs_review",
    started_at: "2026-09-05T10:30:00Z",
    duration_sec: 510,
    crm_outcome: "no_answer_followup",
    overall_score: null,
    result: "Insufficient Evidence",
    customer_phone_masked: "+84***8890",
  },
  {
    id: "cl_1004",
    external_call_id: "dialer-999012",
    agent_user_id: "us_a01",
    agent_name: "Lê Thị Mai",
    campaign_code: "INS-HEALTH",
    status: "scored",
    started_at: "2026-09-05T11:05:00Z",
    duration_sec: 295,
    crm_outcome: "lost",
    overall_score: 54.0,
    result: "fail",
    customer_phone_masked: "+84***3344",
  },
  {
    id: "cl_1005",
    external_call_id: "dialer-999088",
    agent_user_id: "us_a04",
    agent_name: "Võ Quốc Bảo",
    campaign_code: "SOAP-99K",
    status: "scored",
    started_at: "2026-09-05T11:22:00Z",
    duration_sec: 356,
    crm_outcome: "won",
    overall_score: 91.5,
    result: "pass",
    customer_phone_masked: "+84***5566",
  },
  {
    id: "cl_1006",
    external_call_id: "dialer-999120",
    agent_user_id: "us_a02",
    agent_name: "Phạm Minh Đức",
    campaign_code: "EDU-K12",
    status: "processing",
    started_at: "2026-09-05T11:40:00Z",
    duration_sec: 188,
    crm_outcome: null,
    overall_score: null,
    result: null,
    customer_phone_masked: "+84***7788",
  },
];

export const DEMO_ANALYSIS: AnalysisResult = {
  meta: {
    call_id: "cl_1001",
    tenant_id: "tn_acme",
    analyzed_at: "2026-09-05T10:09:13Z",
    pipeline_version: "vcie-3.2.0",
    rulebook_version: "rb-2026.09.01-a3f2",
    sop_id: "sop.fmcg.soap.v8",
    industry_code: "FMCG",
    status: "scored",
    trace_id: "01J9TRACEDEMO001",
  },
  score: 62.5,
  stage_scores: {
    opening: 78,
    discovery: 55,
    pitch: 70,
    objection: 42,
    close: 48,
    outro: 85,
  },
  violations: [
    {
      rule_id: "R-OBJ-PRICE-002",
      severity: "major",
      status: "fail",
      message: "Không tái khung giá trị khi khách từ chối giá 99k",
      evidence_refs: ["ev_12"],
      deduction: 12,
    },
    {
      rule_id: "R-CLOSE-ASK-001",
      severity: "critical",
      status: "fail",
      message: "Thiếu câu chốt rõ ràng sau khi xác nhận nhu cầu",
      evidence_refs: ["ev_18"],
      deduction: 15,
    },
    {
      rule_id: "R-ADDR-001",
      severity: "info",
      status: "Insufficient Evidence",
      message: "Không tìm thấy span địa chỉ giao hàng với độ tin cậy đủ",
      evidence_refs: [],
      deduction: 0,
    },
  ],
  evidence: [
    {
      evidence_id: "ev_01",
      type: "transcript_span",
      speaker: "agent",
      quote: "Dạ em chào chị, em Mai bên chăm sóc khách hàng ạ",
      audio_ts_start: 0.8,
      audio_ts_end: 3.2,
      turn_index: 0,
      confidence: 0.94,
      stage: "opening",
      feature_keys: ["intent.greeting"],
    },
    {
      evidence_id: "ev_08",
      type: "transcript_span",
      speaker: "agent",
      quote: "Chị đang dùng loại dầu gội nào hàng ngày ạ?",
      audio_ts_start: 48.1,
      audio_ts_end: 51.0,
      turn_index: 7,
      confidence: 0.9,
      stage: "discovery",
    },
    {
      evidence_id: "ev_12",
      type: "transcript_span",
      speaker: "customer",
      quote: "99k hơi đắt, chị nghĩ không cần đâu",
      audio_ts_start: 182.4,
      audio_ts_end: 185.6,
      turn_index: 16,
      confidence: 0.92,
      stage: "objection",
      feature_keys: ["intent.price_objection"],
    },
    {
      evidence_id: "ev_13",
      type: "silence",
      speaker: "agent",
      quote: "[im lặng 4.8s sau objection giá]",
      audio_ts_start: 185.6,
      audio_ts_end: 190.4,
      turn_index: 16,
      confidence: 0.99,
      stage: "objection",
      feature_keys: ["silence.after_price"],
    },
    {
      evidence_id: "ev_18",
      type: "transcript_span",
      speaker: "agent",
      quote: "Vậy để em gửi chị thông tin thêm trên Zalo nhé",
      audio_ts_start: 310.2,
      audio_ts_end: 313.8,
      turn_index: 24,
      confidence: 0.88,
      stage: "close",
      feature_keys: ["intent.soft_defer"],
    },
    {
      evidence_id: "ev_20",
      type: "transcript_span",
      speaker: "customer",
      quote: "Cuối tuần chị mới quyết định được",
      audio_ts_start: 298.0,
      audio_ts_end: 301.1,
      turn_index: 23,
      confidence: 0.91,
      stage: "close",
      feature_keys: ["buying_signal.timebox"],
    },
  ],
  root_cause: {
    primary_code: "RC-OBJ-PRICE-UNHANDLED",
    label: "Từ chối giá chưa được xử lý bằng kỹ thuật đối chiếu giá trị",
    confidence: 0.86,
    contributing_factors: [
      "silence_after_price > 4.2s",
      "no_buying_signal_ack",
      "soft_close_missing",
    ],
    evidence_refs: ["ev_12", "ev_13", "ev_18"],
    status: "ok",
    children: [
      {
        code: "RC-OBJ-PRICE-UNHANDLED",
        label: "Không xử lý objection giá",
        weight: 0.45,
        children: [
          { code: "F-SILENCE", label: "Im lặng sau giá", weight: 0.22 },
          { code: "F-NO-REFRAME", label: "Thiếu tái khung giá trị", weight: 0.23 },
        ],
      },
      {
        code: "RC-CLOSE-NO-ASK",
        label: "Không hỏi chốt đơn",
        weight: 0.35,
        children: [
          { code: "F-SOFT-DEFER", label: "Chuyển Zalo thay vì chốt", weight: 0.2 },
          { code: "F-BS-MISS", label: "Bỏ qua buying signal", weight: 0.15 },
        ],
      },
      {
        code: "RC-DISC-SHALLOW",
        label: "Discovery nông",
        weight: 0.2,
      },
    ],
  },
  coaching: {
    priority: "high",
    tips: [
      {
        tip_id: "tip.obj.price.reframe",
        title: "Tái khung giá theo số lần gội / giá trị",
        script_suggestion:
          "Dạ chị ơi, 99k dùng được khoảng 2 tháng, trung bình chưa tới 2 nghìn một lần gội, rẻ hơn chai siêu thị chị đang dùng ạ.",
        linked_rule_ids: ["R-OBJ-PRICE-002"],
        evidence_refs: ["ev_12"],
      },
      {
        tip_id: "tip.close.ask",
        title: "Hỏi chốt rõ ràng khi có buying signal thời gian",
        script_suggestion:
          "Vậy em chốt giúp chị 3 hộp giao thứ Bảy, chị nhận tiền mặt hay chuyển khoản ạ?",
        linked_rule_ids: ["R-CLOSE-ASK-001"],
        evidence_refs: ["ev_20", "ev_18"],
      },
    ],
    drill_ids: ["drill.objection.price.fmcg", "drill.close.ask.basic"],
  },
  revenue_leak: {
    estimated_loss_vnd: 297000,
    leak_codes: ["LEAK_SOFT_CLOSE_MISSING", "LEAK_NO_ALTERNATIVE_OFFER"],
    probability: 0.68,
    explanation:
      "Khách có tín hiệu 'cuối tuần quyết định' nhưng agent không đề xuất chốt giữ chỗ / combo giảm phí ship.",
    evidence_refs: ["ev_20", "ev_18"],
    status: "ok",
  },
  emotion_timeline: [
    { t_sec: 10, progress_pct: 3, valence: 0.35, arousal: 0.4, label: "neutral", speaker: "agent" },
    { t_sec: 50, progress_pct: 13, valence: 0.45, arousal: 0.42, label: "curious", speaker: "customer" },
    { t_sec: 120, progress_pct: 32, valence: 0.2, arousal: 0.55, label: "hesitant", speaker: "customer" },
    { t_sec: 185, progress_pct: 50, valence: -0.45, arousal: 0.7, label: "frustrated", speaker: "customer" },
    { t_sec: 210, progress_pct: 56, valence: -0.2, arousal: 0.5, label: "uncertain", speaker: "agent" },
    { t_sec: 280, progress_pct: 75, valence: 0.05, arousal: 0.35, label: "cooling", speaker: "customer" },
    { t_sec: 340, progress_pct: 91, valence: -0.1, arousal: 0.3, label: "disengaged", speaker: "customer" },
  ],
  conversation_dna: {
    summary:
      "Mở đầu tốt, discovery trung bình; điểm yếu rõ ở objection handling và close assertiveness.",
    dimensions: [
      { key: "rapport", label: "Xây dựng quan hệ", score: 78 },
      { key: "discovery", label: "Khai thác nhu cầu", score: 55 },
      { key: "value", label: "Truyền giá trị", score: 68 },
      { key: "objection", label: "Xử lý từ chối", score: 42 },
      { key: "close", label: "Chốt đơn", score: 48 },
      { key: "compliance", label: "Tuân thủ", score: 86 },
      { key: "emotion", label: "Kiểm soát cảm xúc", score: 58 },
      { key: "clarity", label: "Rõ ràng thông điệp", score: 72 },
    ],
  },
};

export const DEMO_DASHBOARD: DashboardOverview = {
  window: { from: "2026-09-01T00:00:00Z", to: "2026-09-05T23:59:59Z" },
  calls_total: 12450,
  scored: 11890,
  insufficient_evidence: 312,
  failed: 1840,
  avg_score: 76.4,
  auto_fail_rate: 0.074,
  estimated_revenue_leak_vnd: 428500000,
  ie_leak_calls: 89,
  top_failed_rules: [
    { rule_code: "R-CLOSE-ASK-001", title: "Hỏi chốt rõ ràng", fail_count: 1420 },
    { rule_code: "R-OBJ-PRICE-002", title: "Xử lý từ chối giá", fail_count: 980 },
    { rule_code: "R-ADDR-001", title: "Chốt địa chỉ giao hàng", fail_count: 640 },
  ],
  top_root_causes: [
    { cause_code: "RC-CLOSE-NO-ASK", label: "Không hỏi chốt", count: 1100 },
    { cause_code: "RC-OBJ-PRICE-UNHANDLED", label: "Bỏ qua objection giá", count: 860 },
    { cause_code: "RC-DISC-SHALLOW", label: "Discovery nông", count: 420 },
  ],
  employee_scores: [
    {
      user_id: "us_a04",
      full_name: "Võ Quốc Bảo",
      team_name: "HN-Outbound-1",
      avg_score: 89.2,
      calls: 148,
      leak_vnd: 4200000,
      ie_rate: 0.02,
    },
    {
      user_id: "us_a02",
      full_name: "Phạm Minh Đức",
      team_name: "HN-Outbound-1",
      avg_score: 84.5,
      calls: 162,
      leak_vnd: 9800000,
      ie_rate: 0.03,
    },
    {
      user_id: "us_a01",
      full_name: "Lê Thị Mai",
      team_name: "HN-Outbound-1",
      avg_score: 68.1,
      calls: 155,
      leak_vnd: 41200000,
      ie_rate: 0.06,
    },
    {
      user_id: "us_a03",
      full_name: "Hoàng Thu Hà",
      team_name: "SG-Outbound-2",
      avg_score: 71.8,
      calls: 132,
      leak_vnd: 27500000,
      ie_rate: 0.11,
    },
  ],
  kpis: [
    { key: "avg_score", label: "Điểm TB", value: 76.4, unit: "điểm", delta_pct: 2.1 },
    { key: "close_rate_proxy", label: "Tỷ lệ chốt proxy", value: 0.214, unit: "%", delta_pct: -1.4 },
    { key: "objection_handle_rate", label: "Xử lý từ chối", value: 0.61, unit: "%", delta_pct: 3.2 },
    { key: "ie_rate", label: "Tỷ lệ thiếu BC", value: 0.025, unit: "%", delta_pct: -0.4 },
    { key: "appeal_open", label: "Khiếu nại mở", value: 27, unit: "case", delta_pct: 8.0 },
  ],
  stage_heatmap: [
    {
      agent_name: "Võ Quốc Bảo",
      stages: { opening: 92, discovery: 88, pitch: 90, objection: 84, close: 86, outro: 94 },
    },
    {
      agent_name: "Phạm Minh Đức",
      stages: { opening: 86, discovery: 82, pitch: 85, objection: 78, close: 80, outro: 90 },
    },
    {
      agent_name: "Lê Thị Mai",
      stages: { opening: 78, discovery: 55, pitch: 70, objection: 42, close: 48, outro: 85 },
    },
    {
      agent_name: "Hoàng Thu Hà",
      stages: { opening: 80, discovery: 72, pitch: 68, objection: 60, close: 58, outro: null },
    },
  ],
  funnel: [
    { stage: "opening", label: "Mở đầu", count: 11800, rate: 0.94 },
    { stage: "discovery", label: "Khám phá", count: 9800, rate: 0.78 },
    { stage: "pitch", label: "Giới thiệu", count: 8600, rate: 0.68 },
    { stage: "objection", label: "Xử lý từ chối", count: 6100, rate: 0.49 },
    { stage: "close", label: "Chốt sale", count: 4200, rate: 0.33 },
    { stage: "outro", label: "Kết thúc", count: 3900, rate: 0.31 },
  ],
  pareto: [
    { cause_code: "RC-CLOSE-NO-ASK", label: "Không hỏi chốt", count: 1100, share: 0.46, cumulative_share: 0.46 },
    { cause_code: "RC-OBJ-PRICE-UNHANDLED", label: "Bỏ qua objection giá", count: 860, share: 0.36, cumulative_share: 0.82 },
    { cause_code: "RC-DISC-SHALLOW", label: "Discovery nông", count: 420, share: 0.18, cumulative_share: 1.0 },
  ],
  emotion_timeline: [
    { progress_pct: 0, avg_valence: 0.15, samples: 220, label: "neutral" },
    { progress_pct: 20, avg_valence: 0.35, samples: 210, label: "positive" },
    { progress_pct: 40, avg_valence: -0.05, samples: 205, label: "neutral" },
    { progress_pct: 60, avg_valence: -0.32, samples: 198, label: "negative" },
    { progress_pct: 80, avg_valence: 0.12, samples: 180, label: "neutral" },
    { progress_pct: 95, avg_valence: 0.28, samples: 160, label: "positive" },
  ],
  coaching_highlights: [
    { plan_id: "cp_01", agent_user_id: "us_a01", title: "Luyện hỏi chốt 3 câu", priority: "critical", status: "active" },
    { plan_id: "cp_02", agent_user_id: "us_a03", title: "Xử lý objection giá bằng value stack", priority: "major", status: "open" },
  ],
};

export const DEMO_RULES: RulebookRule[] = [
  {
    rule_code: "R-OPEN-001",
    category: "opening",
    title: "Chào khách hàng",
    description: "Agent phải chào và xưng tên trong 15 giây đầu.",
    severity: "major",
    weight: 1.35,
    auto_fail: false,
    status: "active",
    evaluator_type: "span_classifier",
    version: 3,
  },
  {
    rule_code: "R-DISC-NEED-001",
    category: "discovery",
    title: "Hỏi nhu cầu / tình trạng hiện tại",
    description: "Phải có ít nhất một câu hỏi discovery trước khi pitch.",
    severity: "major",
    weight: 1.4,
    auto_fail: false,
    status: "active",
    evaluator_type: "span_classifier",
    version: 2,
  },
  {
    rule_code: "R-OBJ-PRICE-002",
    category: "objection",
    title: "Xử lý từ chối giá",
    description: "Khi khách nêu giá đắt, agent phải tái khung giá trị trong 2 lượt.",
    severity: "major",
    weight: 1.6,
    auto_fail: false,
    status: "active",
    evaluator_type: "llm_judge",
    version: 5,
  },
  {
    rule_code: "R-CLOSE-ASK-001",
    category: "close",
    title: "Hỏi chốt rõ ràng",
    description: "Phải có câu hỏi chốt đơn / đặt lịch rõ ràng trước khi kết thúc.",
    severity: "critical",
    weight: 1.8,
    auto_fail: true,
    status: "active",
    evaluator_type: "span_classifier",
    version: 4,
  },
  {
    rule_code: "R-ADDR-001",
    category: "close",
    title: "Chốt địa chỉ giao hàng",
    description: "Thu thập địa chỉ đầy đủ khi CRM outcome = won hoặc callback confirmed.",
    severity: "major",
    weight: 1.4,
    auto_fail: false,
    status: "active",
    evaluator_type: "slot_extractor",
    version: 2,
  },
  {
    rule_code: "R-COMP-PRICE-002",
    category: "compliance",
    title: "Công bố giá đúng",
    description: "Không được nêu giá khác với bảng giá campaign đang active.",
    severity: "critical",
    weight: 2.0,
    auto_fail: true,
    status: "active",
    evaluator_type: "regex_slot",
    version: 1,
  },
];

export const DEMO_COACHING_PLANS: CoachingPlan[] = [
  {
    id: "cp_01",
    agent_user_id: "us_a01",
    agent_name: "Lê Thị Mai",
    period_start: "2026-09-01",
    period_end: "2026-09-07",
    status: "in_progress",
    focus_areas: ["Xử lý từ chối giá", "Câu chốt đơn"],
    items: [
      {
        id: "cpi_1",
        title: "Drill tái khung giá FMCG",
        tip_id: "tip.obj.price.reframe",
        status: "open",
        drill_id: "drill.objection.price.fmcg",
        script:
          "Dạ chị ơi, quy ra mỗi lần gội chưa tới 2 nghìn — rẻ hơn chai chị đang dùng.",
      },
      {
        id: "cpi_2",
        title: "Hỏi chốt sau buying signal",
        tip_id: "tip.close.ask",
        status: "done",
        drill_id: "drill.close.ask.basic",
        script: "Em chốt giúp chị 3 hộp giao thứ Bảy nhé?",
      },
    ],
    roleplay_scenarios: [
      {
        id: "rp_1",
        title: "Khách: '99k đắt quá'",
        objection: "99k hơi đắt, chị nghĩ không cần đâu",
        expected_script:
          "Tái khung giá trị + hỏi chốt combo 2 hộp freeship",
        difficulty: "medium",
      },
      {
        id: "rp_2",
        title: "Khách: 'Cuối tuần mới quyết'",
        objection: "Cuối tuần chị mới quyết định được",
        expected_script: "Acknowledge + đề xuất giữ chỗ / giao cuối tuần",
        difficulty: "hard",
      },
    ],
  },
  {
    id: "cp_02",
    agent_user_id: "us_a03",
    agent_name: "Hoàng Thu Hà",
    period_start: "2026-09-01",
    period_end: "2026-09-07",
    status: "open",
    focus_areas: ["Giảm Insufficient Evidence", "Discovery sâu hơn"],
    items: [
      {
        id: "cpi_3",
        title: "Thu thập địa chỉ rõ ràng",
        tip_id: "tip.addr.collect",
        status: "open",
        script: "Chị cho em xin địa chỉ nhận hàng đầy đủ: số nhà, đường, quận ạ?",
      },
    ],
    roleplay_scenarios: [
      {
        id: "rp_3",
        title: "Khách nói nhỏ / nhiễu audio",
        objection: "Audio kém — xác nhận lại thông tin",
        expected_script: "Nhắc lại + xác nhận từng field",
        difficulty: "easy",
      },
    ],
  },
];

export const DEMO_QA_QUEUE: QaQueueItem[] = [
  {
    call_id: "cl_1003",
    agent_name: "Hoàng Thu Hà",
    queue: "ie_heavy",
    score: null,
    confidence: 0.41,
    flagged_at: "2026-09-05T10:45:00Z",
    reason: "≥3 rule Insufficient Evidence; cần human review",
  },
  {
    call_id: "cl_1001",
    agent_name: "Lê Thị Mai",
    queue: "calibration",
    score: 62.5,
    confidence: 0.78,
    flagged_at: "2026-09-05T10:10:00Z",
    reason: "Mẫu calibration tuần 36 — đối chiếu human label",
  },
  {
    call_id: "cl_1004",
    agent_name: "Lê Thị Mai",
    queue: "compliance",
    score: 54.0,
    confidence: 0.84,
    flagged_at: "2026-09-05T11:08:00Z",
    reason: "Industry INS risk_tier=high + violation compliance",
  },
  {
    call_id: "cl_1002",
    agent_name: "Phạm Minh Đức",
    queue: "low_confidence",
    score: 88.0,
    confidence: 0.52,
    flagged_at: "2026-09-05T10:20:00Z",
    reason: "Model confidence dưới ngưỡng tenant config",
  },
];

export const DEMO_APPEALS: Appeal[] = [
  {
    id: "ap_01",
    call_id: "cl_1001",
    agent_name: "Lê Thị Mai",
    rule_code: "R-CLOSE-ASK-001",
    rule_title: "Hỏi chốt rõ ràng",
    current_verdict: "fail",
    proposed_verdict: "pass",
    reason_code: "evidence_misheard",
    reason_text: "Agent đã hỏi chốt lúc phút 5:02 nhưng STT miss",
    status: "under_review",
    created_at: "2026-09-05T11:30:00Z",
    evidence_quote: "Em giao cho chị 3 hộp chiều nay được không ạ?",
  },
  {
    id: "ap_02",
    call_id: "cl_1004",
    agent_name: "Lê Thị Mai",
    rule_code: "R-COMP-PRICE-002",
    rule_title: "Công bố giá đúng",
    current_verdict: "fail",
    proposed_verdict: "not_applicable",
    reason_code: "wrong_campaign_context",
    reason_text: "Cuộc gọi là CSKH không bán mới",
    status: "open",
    created_at: "2026-09-05T12:00:00Z",
  },
  {
    id: "ap_03",
    call_id: "cl_1002",
    agent_name: "Phạm Minh Đức",
    rule_code: "R-OBJ-PRICE-002",
    rule_title: "Xử lý từ chối giá",
    current_verdict: "fail",
    proposed_verdict: "pass",
    reason_code: "evidence_complete",
    reason_text: "Đã tái khung đúng SOP",
    status: "overturned",
    created_at: "2026-09-04T16:20:00Z",
    evidence_quote: "Quy ra mỗi lần gội chưa tới 2 nghìn ạ",
  },
];

export const DEMO_USERS: AdminUser[] = [
  {
    id: "us_demo_001",
    email: "lead@acme.vn",
    full_name: "Nguyễn Văn Lead",
    roles: ["team_lead"],
    team_name: "HN-Outbound-1",
    active: true,
    last_login_at: "2026-09-05T08:00:00Z",
  },
  {
    id: "us_qa_001",
    email: "qa@acme.vn",
    full_name: "Trần QA Manager",
    roles: ["qa_manager", "admin"],
    team_name: "QA Central",
    active: true,
    last_login_at: "2026-09-05T07:30:00Z",
  },
  {
    id: "us_a01",
    email: "mai.le@acme.vn",
    full_name: "Lê Thị Mai",
    roles: ["agent"],
    team_name: "HN-Outbound-1",
    active: true,
    last_login_at: "2026-09-05T09:50:00Z",
  },
  {
    id: "us_a02",
    email: "duc.pham@acme.vn",
    full_name: "Phạm Minh Đức",
    roles: ["agent"],
    team_name: "HN-Outbound-1",
    active: true,
    last_login_at: "2026-09-05T09:55:00Z",
  },
  {
    id: "us_a03",
    email: "ha.hoang@acme.vn",
    full_name: "Hoàng Thu Hà",
    roles: ["agent"],
    team_name: "SG-Outbound-2",
    active: false,
    last_login_at: "2026-09-03T18:10:00Z",
  },
];
